services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"

  frontend:
    image: node:20-alpine
    working_dir: /app
    container_name: frontend-dev
    environment:
      - VITE_API_TARGET=http://backend:8001
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  frontend_node_modules:

